# Generated by Django 5.2.4 on 2025-07-24 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the API key', max_length=255)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('key_type', models.CharField(choices=[('FULL_ACCESS', 'Full Access'), ('READ_ONLY', 'Read Only'), ('ANALYSIS_ONLY', 'Analysis Only'), ('REPORTING_ONLY', 'Reporting Only')], default='READ_only', max_length=20)),
                ('allowed_ips', models.JSONField(default=list, help_text='List of allowed IP addresses')),
                ('rate_limit', models.IntegerField(default=100, help_text='Requests per hour')),
                ('total_requests', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('SECURITY_ANALYST', 'Security Analyst'), ('IT_STAFF', 'IT Staff'), ('GENERAL_USER', 'General User'), ('VIEWER', 'Viewer')], default='GENERAL_USER', max_length=20)),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('SECURITY', 'Cybersecurity'), ('OPERATIONS', 'Operations'), ('MANAGEMENT', 'Management'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('dashboard_layout', models.JSONField(default=dict, help_text='User dashboard preferences')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_score', models.FloatField(default=0.0, help_text='Risk score from 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('ANALYSIS_CREATE', 'Analysis Created'), ('ANALYSIS_VIEW', 'Analysis Viewed'), ('ANALYSIS_UPDATE', 'Analysis Updated'), ('ANALYSIS_DELETE', 'Analysis Deleted'), ('REPORT_GENERATE', 'Report Generated'), ('REPORT_EXPORT', 'Report Exported'), ('THREAT_FEED_UPDATE', 'Threat Feed Updated'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('PERMISSION_CHANGE', 'Permission Changed'), ('SYSTEM_CONFIG', 'System Configuration Changed'), ('API_ACCESS', 'API Access'), ('FILE_UPLOAD', 'File Uploaded'), ('FILE_DOWNLOAD', 'File Downloaded'), ('SECURITY_ALERT', 'Security Alert'), ('ERROR', 'System Error')], max_length=25)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_data', models.JSONField(default=dict, help_text='Additional context data')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='user_manage_user_id_8eb8c0_idx'), models.Index(fields=['activity_type', 'timestamp'], name='user_manage_activit_e4e36a_idx'), models.Index(fields=['ip_address', 'timestamp'], name='user_manage_ip_addr_85fd55_idx')],
            },
        ),
    ]
